name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'csharp'
        queries: security-and-quality
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/OctoshiftCLI.sln
    - name: Build
      run: dotnet build src/OctoshiftCLI.sln --no-restore
    - name: Unit Test
      run: dotnet test src/OctoshiftCLI.sln --filter FullyQualifiedName\!~Integration --no-build --verbosity normal
    - name: Integration Test
      env: 
        ADO_PAT: ${{ secrets.ADO_PAT }}
      run: dotnet test src/OctoshiftCLI.sln --filter FullyQualifiedName\~Integration --no-build --verbosity normal
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    - name: Create Distributable Binaries
      run: ./publish.ps1
      shell: pwsh
    - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

